INSERT INTO TODOS(ID, TASK, IS_DONE, IS_ACTIVE, CREATED_AT) VALUES (1, 'Dar banho no gato', 0, 1, SYSDATE);
INSERT INTO TODOS(ID, TASK, IS_DONE, IS_ACTIVE, CREATED_AT) VALUES (2, 'Pegar as comprar', 0, 1, SYSDATE);
INSERT INTO TODOS(ID, TASK, IS_DONE, IS_ACTIVE, CREATED_AT) VALUES (3, 'Limpar as compras', 0, 1, SYSDATE);