INSERT INTO TODOS(ID, TASK, IS_DONE, IS_ACTIVE, CREATED_AT) VALUES (TODO_SEQ_ID.NEXTVAL, 'Ir ao mercado', 0, 1, SYSDATE);
INSERT INTO TODOS(ID, TASK, IS_DONE, IS_ACTIVE, CREATED_AT) VALUES (TODO_SEQ_ID.NEXTVAL, 'Dar banho nos cachorros', 0, 1, SYSDATE);
INSERT INTO TODOS(ID, TASK, IS_DONE, IS_ACTIVE, CREATED_AT) VALUES (TODO_SEQ_ID.NEXTVAL, 'Dar banho no gato', 0, 1, SYSDATE);
INSERT INTO TODOS(ID, TASK, IS_DONE, IS_ACTIVE, CREATED_AT) VALUES (TODO_SEQ_ID.NEXTVAL, 'Lavar o carro', 0, 1, SYSDATE);
INSERT INTO TODOS(ID, TASK, IS_DONE, IS_ACTIVE, CREATED_AT) VALUES (TODO_SEQ_ID.NEXTVAL, 'Trocar as janelas', 0, 1, SYSDATE);
INSERT INTO TODOS(ID, TASK, IS_DONE, IS_ACTIVE, CREATED_AT) VALUES (TODO_SEQ_ID.NEXTVAL, 'Ligar para o mecânico', 0, 1, SYSDATE);
INSERT INTO TODOS(ID, TASK, IS_DONE, IS_ACTIVE, CREATED_AT) VALUES (TODO_SEQ_ID.NEXTVAL, 'Fazer tarefa do inglês', 0, 1, SYSDATE);
